In [59]:
import numpy as np

In [140]:
a = np.arange(1,17)
print(a)

In [161]:
x = np.array([0.45, 5, 1, 6, 1.6, 6.31, 2.16, 6.63, 2.91, 6.97, 3.93,7.33, 5.3, 7.7, 7.16, 8.4])
xu = np.array([5.00, 6.00, 6.31, 6.63, 6.97, 7.33, 7.70])
# xu=np.array([14.47, 14.76, 15.39, 14.52])
xl = np.array([1.00, 1.60, 2.16, 2.91, 3.93, 5.30, 7.16])

In [162]:
def array_add_x1(x, step):
    result = [x[0]]
    sum_temp = x[0]
    for i in range(1,len(x)):
        sum_temp += step * x[i]
        result.append(sum_temp)
    return np.array(result)


In [167]:
xu1 = array_add_x1(xu, 2)
xl1 = array_add_x1(xl,2)
print(xu1)
print(xl1)


[ 5.   17.   29.62 42.88 56.82 71.48 86.88]
[ 1.    4.2   8.52 14.34 22.2  32.8  47.12]


In [164]:
def z_array(x1):
    result = []
    for i in range(1, len(x1)):
        result.append(0.5 * (x1[i] + x1[i - 1]))
    return np.array(result)


In [169]:
zu = z_array(xu1)
zl=z_array(xl1)
print(zu)
print(zl)

[11.   23.31 36.25 49.85 64.15 79.18]
[ 2.6   6.36 11.43 18.27 27.5  39.96]


In [170]:
Bu = np.vstack((-zu, np.ones(len(zu)))).T
Yu = xu.T[1:]
Au = np.linalg.inv(Bu.T.dot(Bu)).dot(Bu.T).dot(Yu)
Bl = np.vstack((-zl, np.ones(len(zl)))).T
Yl = xl.T[1:]
Al = np.linalg.inv(Bl.T.dot(Bl)).dot(Bl.T).dot(Yl)
print(Bu)
print(Au)
print(Au[1]/Au[0])
print(Al[1]/Al[0])


[[-11.     1.  ]
 [-23.31   1.  ]
 [-36.25   1.  ]
 [-49.85   1.  ]
 [-64.15   1.  ]
 [-79.18   1.  ]]
[-0.02494548  5.72681303]
-229.57314285714315
-8.144660041841016
