In [30]:
import numpy as np
import matplotlib.pyplot as plt

# 论文数值实验

In [78]:
# x = np.array([0.45, 5, 1, 6, 1.6, 6.31, 2.16, 6.63, 2.91, 6.97, 3.93, 7.33, 5.3, 7.7, 7.16, 8.4])
xu = np.array([5.00, 6.00, 6.31, 6.63, 6.97, 7.33, 7.70])
tu = [2, 4, 6, 8, 10, 12, 14]
xl = np.array([1.00, 1.60, 2.16, 2.91, 3.93, 5.30, 7.16])
tl = [3, 5, 7, 9, 11, 13, 15]

# 论文中应用

In [46]:
xu = np.array([14.47, 14.76, 15.39, 14.52])
tu = np.array([2, 4, 6, 9])
xl = np.array([13.95, 13.37, 14.41, 14.44, 13.61])
tl = np.array([1, 3, 5, 7, 8])

In [97]:
xu = np.array([488885,
               561816,
               577566,
               610019,
               640778,
               583522,
               597543,
               674047,
               691994,
               683005])
tu = np.array([2, 3, 5, 7, 8, 10, 11, 12, 15, 17])
xl = np.array([540464,
               566903,
               567082,
               586802,
               500690,
               658777,
               644084])
tl = np.array([4, 6, 9, 13, 14, 16, 18])

In [110]:
xu = np.array([22711, 28111,
               26106,
               28343,
               28658,
               25260,
               26749,
               25395,
               31712,
               30337])
tu = np.array([2, 3, 5, 7, 8, 10, 11, 13, 15, 17])
xl = np.array([25044,
               26102,
               24891,
               24942,
               18025,
               28793,
               28020])
tl = np.array([4, 6, 9, 12, 14, 16, 18])

# excel第三组

In [127]:
xu = np.array([35137,44790,
               44093,
               47382,
               47666,
               48195,
               52846,
               55437,
               52972])
tu = np.array([1,3, 5, 7, 8, 11, 12, 15, 17])
xl = np.array([33385,
               42099,
               42730,
               44585,
               43792,
               45794,
               36387,
               51199,
               50425])
tl = np.array([2, 4, 6, 9, 10, 13, 14, 16, 18])

In [128]:
def array_add_x1(x, step):
    result = [x[0]]
    sum_temp = x[0]
    for i in range(1,len(x)):
        sum_temp += (step[i]-step[i-1]) * x[i]
        result.append(sum_temp)
    return np.array(result)

In [129]:
xu1 = array_add_x1(xu, tu)
xl1 = array_add_x1(xl,tl)
# x1 = array_add_x1(x,1)
print(xu1)
print(xl1)

[ 35137 124717 212903 307667 355333 499918 552764 719075 825019]
[ 33385 117583 203043 336798 380590 517972 554359 656757 757607]


In [130]:
def z_array(x1):
    result = []
    for i in range(1, len(x1)):
        result.append(0.5 * (x1[i] + x1[i - 1]))
    return np.array(result)

In [131]:
zu = z_array(xu1)
zl=z_array(xl1)
print(zu)
print(zl)

[ 79927.  168810.  260285.  331500.  427625.5 526341.  635919.5 772047. ]
[ 75484.  160313.  269920.5 358694.  449281.  536165.5 605558.  707182. ]


In [132]:
Bu = np.vstack((-zu, np.ones(len(zu)))).T
Yu = xu.T[1:]
Au = np.linalg.inv(Bu.T.dot(Bu)).dot(Bu.T).dot(Yu)
Bl = np.vstack((-zl, np.ones(len(zl)))).T
Yl = xl.T[1:]
Al = np.linalg.inv(Bl.T.dot(Bl)).dot(Bl.T).dot(Yl)
print(Au)
print(Al)

[-1.60114398e-02  4.27631356e+04]
[-9.98376180e-03  4.06795469e+04]


In [133]:
import math

t = np.linspace(2, 25, 1000)
xu_f = [(xu1[0] - Au[1] / Au[0]) * math.exp(-Au[0] * (i - tu[0])) + Au[1] / Au[0] for i in t]
xl_f = [(xl1[0] - Al[1] / Al[0]) * math.exp(-Al[0] * (i - tl[0])) + Al[1] / Al[0] for i in t]

plt.plot(t, xu_f)
plt.plot(t,xl_f)
plt.show()

In [134]:
min_index = 0
min_diff = 100000
minus = np.fabs(np.array(xu_f) - np.array(xl_f))
t[np.where(minus == np.min(minus))[0][0]]

2.0

In [135]:
xu_f_in = [(xu1[0] - Au[1] / Au[0]) * math.exp(-Au[0] * (i - tu[0])) + Au[1] / Au[0] for i in range(1,25)]
xu_f_in

[35137.0,
 78811.4418195025,
 123190.80266052764,
 168286.46013447084,
 214109.97549090022,
 260673.09658153076,
 307987.76087204786,
 356066.0985025298,
 404920.435397272,
 454563.29642480845,
 505007.4086089311,
 556265.7043915391,
 608351.3249481493,
 661277.6235569245,
 715058.1690220721,
 769706.7491525039,
 825237.3742966396,
 881664.2809342612,
 939001.9353263462,
 997265.0372238066,
 1056468.5236360868,
 1116627.572660591,
 1177757.6073739198,
 1239874.2997859055]

In [136]:
xl_f_in = [(xl1[0] - Al[1] / Al[0]) * math.exp(-Al[0] * (i - tl[0])) + Al[1] / Al[0] for i in range(1,25)]
xl_f_in

[-7423.803096767515,
 33385.0,
 74603.26907038735,
 116235.11260008533,
 158284.68029836705,
 200756.16351171723,
 243653.79564160807,
 286981.8525664746,
 330744.65306790965,
 374946.559261153,
 419591.97702988563,
 464685.35646539414,
 510231.19231014,
 556234.0244057742,
 602698.4381456603,
 649629.0649319212,
 697030.5826370879,
 744907.7160703647,
 793265.2374485903,
 842107.9668719037,
 891440.7728042039,
 941268.5725584156,
 991596.3327866276,
 1042429.0699751587]

In [94]:
t

array([ 2.        ,  2.02302302,  2.04604605,  2.06906907,  2.09209209,
        2.11511512,  2.13813814,  2.16116116,  2.18418418,  2.20720721,
        2.23023023,  2.25325325,  2.27627628,  2.2992993 ,  2.32232232,
        2.34534535,  2.36836837,  2.39139139,  2.41441441,  2.43743744,
        2.46046046,  2.48348348,  2.50650651,  2.52952953,  2.55255255,
        2.57557558,  2.5985986 ,  2.62162162,  2.64464464,  2.66766767,
        2.69069069,  2.71371371,  2.73673674,  2.75975976,  2.78278278,
        2.80580581,  2.82882883,  2.85185185,  2.87487487,  2.8978979 ,
        2.92092092,  2.94394394,  2.96696697,  2.98998999,  3.01301301,
        3.03603604,  3.05905906,  3.08208208,  3.10510511,  3.12812813,
        3.15115115,  3.17417417,  3.1971972 ,  3.22022022,  3.24324324,
        3.26626627,  3.28928929,  3.31231231,  3.33533534,  3.35835836,
        3.38138138,  3.4044044 ,  3.42742743,  3.45045045,  3.47347347,
        3.4964965 ,  3.51951952,  3.54254254,  3.56556557,  3.58

In [95]:
xu_f

[488885.0,
 501822.0081362054,
 514763.4700504765,
 527709.3872760981,
 540659.7613468692,
 553614.5937971473,
 566573.8861617967,
 579537.6399762183,
 592505.8567763492,
 605478.5380986258,
 618455.6854800433,
 631437.3004581183,
 644423.3845708966,
 657413.9393569455,
 670408.966355361,
 683408.467105791,
 696412.4431484044,
 709420.8960238695,
 722433.827273421,
 735451.2384388149,
 748473.1310623363,
 761499.5066867992,
 774530.3668555543,
 787565.7131124735,
 800605.5470019653,
 813649.8700689822,
 826698.6838589907,
 839751.9899179935,
 852809.7897925228,
 865872.0850296691,
 878938.877177015,
 892010.167782709,
 905085.958395414,
 918166.2505643219,
 931251.045839183,
 944340.3457702622,
 957434.151908353,
 970532.4658048004,
 983635.289011471,
 996742.6230807751,
 1009854.46956563,
 1022970.8300195411,
 1036091.705996491,
 1049217.099051036,
 1062347.0107382461,
 1075481.4426137432,
 1088620.3962336704,
 1101763.8731547222,
 1114911.874934107,
 1128064.403129585,
 1141221.45929

In [96]:
xl_f

[-536722.2190282121,
 -524444.5874190405,
 -512164.123318851,
 -499880.826074183,
 -487594.6950314194,
 -475305.7295367941,
 -463013.9289363846,
 -450719.2925761342,
 -438421.8198018074,
 -426121.5099590421,
 -413818.3623933196,
 -401512.37644996494,
 -389203.551474154,
 -376891.8868109137,
 -364577.38180511445,
 -352260.0358014852,
 -339939.8481445983,
 -327616.81817887723,
 -315290.945248574,
 -302962.22869782895,
 -290630.66787059605,
 -278296.2621107027,
 -265959.0107618049,
 -253618.9131674096,
 -241275.96867088974,
 -228930.17661545426,
 -216581.53634416312,
 -204230.04719991237,
 -191875.70852546394,
 -179518.5196634233,
 -167158.4799562469,
 -154795.58874621987,
 -142429.84537550062,
 -130061.24918609113,
 -117689.79951982945,
 -105315.4957184121,
 -92938.33712337911,
 -80558.32307611406,
 -68175.45291786641,
 -55789.725989714265,
 -43401.14163258672,
 -31009.699187278748,
 -18615.39799440652,
 -6218.237394452095,
 6181.783272251487,
 18584.664665535092,
 30990.407445393503,
 4